### PR TITLE
Complete address settings properties

### PR DESCRIPTION
**Pull request by gaohoward**
Hi @zkraus, 

Can you merge this. It has full address settings parameters.

Thanks
Howard

### CODE REVIEW

**Comment by zkraus** [comment]
Hello @gaohoward,

whoa, that's a lot of new options, ok, we also need to modify the template in a similar fashion, I am not quite sure if there is just one address_settings template (hopefully there is). This is the ideal place to start https://github.com/zkraus/yacfg/blob/master/src/yacfg/templates/artemis/2.14.0/modules/broker_xml/address_settings.jinja2 If would not have a chance to look at that, I will try to modify it later today.

Thanks,
Zdenek

**Comment by gaohoward** [comment]
Thanks @zkraus . yes there are a lost more. Please let me to do it and update the pr.

**Comment by zkraus** [comment]
I think there is only one address_settings.jinja2 template per version, so if you identify the version that those options apply to, you can just copy the file to the specific versions, since they are currently identical.

Then it would be good to distribute the user_address_settings.yaml.jinja2 profile module to those versions as well.


`
src/yacfg/templates/artemis/2.13.0/modules/broker_xml/address_settings.jinja2:        <address-settings>
src/yacfg/templates/artemis/2.14.0/modules/broker_xml/address_settings.jinja2:        <address-settings>
src/yacfg/templates/artemis/2.5.0/modules/broker_xml/address_settings.jinja2:        <address-settings>
src/yacfg/templates/artemis/2.6.0/modules/broker_xml/address_settings.jinja2:        <address-settings>
src/yacfg/templates/artemis/2.9.0/modules/broker_xml/address_settings.jinja2:        <address-settings>
`

**Comment by gaohoward** [comment]
@zkraus ok thanks. I'll check the other versions. I've just updated 2.14.0.

**Comment by gaohoward** [comment]
@zkraus Hi Zdenek I've added address settings to all the templates. Pls take a look.
thanks

**Review by zkraus — APPROVED** [review]

**Pull request merged**
